version: 2
services:
  - type: web
    name: automated-job-backend
    env: python
    buildCommand: "./build.sh"
    startCommand: "python start.py"
    plan: free
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.0
      - key: PORT
        fromService: 
          type: web
          name: automated-job-backend
          property: port
      - key: HOST
        value: 0.0.0.0
      - key: ENVIRONMENT
        value: production